name: Arch Linux Haxefetch repo container

on:
  release:
    types: [published]

jobs:
  build-arch-repo:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm base-devel git repo-add

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Prepare Build Directory
        run: |
          useradd builder -m
          chown -R builder:builder .

      - name: Build Arch Package
        run: |
          su builder -c "updpkgsums"
          su builder -c "makepkg -s --noconfirm"

      - name: Update Repository Database
        run: |
          mkdir -p x86_64
          cp *.pkg.tar.zst x86_64/
          cd x86_64
          repo-add haxefetch.db.tar.zst *.pkg.tar.zst
          
          # Maintain symlinks for pacman compatibility
          rm -f haxefetch.db haxefetch.files
          cp haxefetch.db.tar.zst haxefetch.db
          [ -f haxefetch.files.tar.zst ] && cp haxefetch.files.tar.zst haxefetch.files

      - name: Deploy to GitHub Pages / Repo Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./x86_64
          keep_files: true